name: ourverse.tf
on:
  push:
    branch: [development]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: pushing latest change on nomads.ourworld.tf
        uses: appleboy/ssh-action@master
        with:
          host: nomads.ourworld.tf
          username: webuser
          key: ${{ secrets.TF_SECRET }}
          port: 34022
          script: |
            cd /home/webuser/websites/www2/www_ournomads/
            git log -1
            git pull
            bash build.sh
